nyc_taxi:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: nyc-taxi-data-pipeline-507015
      dataset: nyc_taxi_dbt
      keyfile: "{{ env_var('GCP_KEYFILE_PATH', '/app/gcp_service_account.json') }}"
      threads: 4
      timeout_seconds: 300
      location: US
