version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-local

    environment:
      POSTGRES_DB: nyc_taxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "-c shared_preload_libraries=uuid-ossp"

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ../warehouse/ddl:/docker-entrypoint-initdb.d/ddl:ro

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - nyc-taxi-net

    restart: unless-stopped

  spark-etl:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.spark

    container_name: spark-etl-container
    ports:
      - "4040:4040"

    env_file:
      - ../../.env

    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DATABASE=nyc_taxi

    volumes:
      - ../../data:/app/data
      - ../../infrastructure:/app/infrastructure:ro

    networks:
      - nyc-taxi-net

    restart: "no"

    depends_on:
      postgres:
        condition: service_healthy

  dbt:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.dbt

    container_name: dbt-transformer-container

    env_file:
      - ../../.env

    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DATABASE=nyc_taxi

    volumes:
      - ../../dbt:/app/dbt
      - ../../infrastructure:/app/infrastructure:ro
      - ../../data:/app/data             # Manifest + cleanup raw/processed sau dbt test
      - ../../spark:/app/spark:ro        # finalize.py overrides image copy khi dev

    networks:
      - nyc-taxi-net

    restart: "no"

    depends_on:
      spark-etl:
        condition: service_completed_successfully

volumes:
  postgres_data:

networks:
  nyc-taxi-net:
    driver: bridge
